### PR TITLE
Webapp dashboard

### PR DESCRIPTION
**Pull request by duboisph**
Adds a generic dashboard for basic webapp monitoring, which can be used in our customer's setups.

Example of the running dashboard: https://grafana.kops.staging.apptweak.com/dashboard/db/web-app-metrics-test?orgId=1&from=now-3h&to=now

Related issue: skyscrapers/runtime/issues/65

### CODE REVIEW

**Comment by SamClinckspoor** [comment]
Not all the graphs seem to be responding to the deployment filter

**Comment by duboisph** [comment]
That's because those deployments don't expose the http metrics

**Comment by duboisph** [comment]
@SamClinckspoor Ok, only apps exporting `http_requests_total` will show up, from the customer's Prometheus + some minor graph tweaks.

Example dashboard: https://grafana.kops.staging.apptweak.com/dashboard/db/web-app-metrics-test?orgId=1&from=now-3h&to=now

**Comment by SamClinckspoor** [comment]
There is still a bug in some graphs where a container shows up not selected in the deployment filter:
screen shot 2018-05-22 at 10 31 07

**Comment by duboisph** [comment]
I tried fixing that, but now sure how I can. It checks on the deployment name with a `.*` so to select all the containers in the deployment. Unfortunately this also selects the other  deployments.

So this bug is more an issue how the AppTweak deployments are named.

**Pull request merged**
